<?php
/** @var \MaxServ\YoastSeo\Block\Adminhtml\YoastBox $block */
?>
<div id="yoast-seo-wrapper" class="yoastBox">
    <ul class="yoastBox-tabs">
        <li class="yoastBox-tabs-tab">
            <a href="#yoast-seo-overview" title="<?php echo __('Analysis'); ?>"><?php echo __('Analysis'); ?></a>
        </li>
        <li class="yoastBox-tabs-tab">
            <a href="#yoast-seo-facebook" title="<?php echo __('Facebook'); ?>"><?php echo __('Facebook'); ?></a>
        </li>
        <li class="yoastBox-tabs-tab">
            <a href="#yoast-seo-twitter" title="<?php echo __('Twitter'); ?>"><?php echo __('Twitter'); ?></a>
        </li>
        <li class="yoastBox-tabs-tab">
            <a href="#yoast-seo-keywords" title="<?php echo __('Keywords'); ?>"><?php echo __('Keywords'); ?></a>
        </li>
    </ul>
    <div id="yoast-seo-overview" class="yoastBox-tab">
        <div class="analysisBox analysisBox--readability" data-mage-init='{"collapsible":{"active":true}}'>
            <h3 data-role="title">
                <span id="readability-overallScore" class="overallScore"></span>
                <span><?php echo __('Readability'); ?></span>
            </h3>
            <div data-role="content">
                <p>
                    <?php echo __('This is the content analysis, a collection of content checks that analyze the content of your page.'); ?>
                    <a href="#"><?php echo __('Learn more about the Content Analysis Tool'); ?>.</a>
                </p>
                <div id="yoast-seo-content-output"></div>
            </div>
        </div>
        <div class="analysisBox analysisBox--keyword" data-mage-init='{"collapsible":{"active":true}}'>
            <h3 data-role="title">
                <span id="seo-overallScore" class="overallScore"></span>
                <span><?php echo __('Focus keyword'); ?>:</span>
                <span class="seo-focusKeyword"></span>
            </h3>
            <div data-role="content">
                <div id="yoast-seo-focus-input">
                    <fieldset id="yoast-seo-focus-input-fieldset" class="admin__fieldset"></fieldset>
                </div>
                <div id="yoast-seo-snippet-preview"></div>
                <div id="yoast-seo-output"></div>
            </div>
        </div>
    </div>
    <div id="yoast-seo-facebook" class="yoastBox-tab">
        <h3><?php echo __('Facebook settings'); ?></h3>
        <p><?php echo __('These settings will override the default settings for'); ?> Facebook</p>
    </div>
    <div id="yoast-seo-twitter" class="yoastBox-tab">
        <h3><?php echo __('Twitter settings'); ?></h3>
        <p><?php echo __('These settings will override the default settings for'); ?> Twitter</p>
    </div>
    <div id="yoast-seo-keywords" class="yoastBox-tab">
        <fieldset id="yoast-seo-keywords-fieldset" class="admin__fieldset"></fieldset>
    </div>
</div>
<script>
    require(['yoastSeo'], function(yoastSeo) {
        yoastSeo();
    });
</script>
